### ISSUE TITLE
Remove mục "Mua"

### ISSUE THREAD

**Issue by JustBrianZ** [gtav-mp/issues#6]
![image](https://user-images.githubusercontent.com/101466788/187905831-d0e89c50-8d4e-4371-99d5-d8004a7e2bd6.png)

**Comment by BrianfromRageVN** [comment]
Remove luôn chức "Mua" luôn, chỉ giữ lại mua tất cả và huỷ bỏ thôi, mà xíu mình cũng sẽ fix về lại là thanh toán.
