### ISSUE TITLE
Remove [E] và chỉnh là phạm vi.

### ISSUE THREAD

**Issue by JustBrianZ** [gtav-mp/issues#9]
![image](https://user-images.githubusercontent.com/101466788/189156137-907d418b-3d31-4c53-8300-8cb79f09cffb.png)

Xoá hiển thị chữ [E] khi lại gần chiếc xe, nhưng chức năng vẫn vậy chỉ là người chơi sẽ ko thấy chữ E nữa , họ chỉ cần lại gần đó nhấn E là được , đừng để hiển thị lên.
+ Đồng thời xoá chứ [E] khi lại gần nhân vật của từng người luôn.

Cái thứ 2, chỉnh lại khoảng cách khi đừng gần chữ E.
![image](https://user-images.githubusercontent.com/101466788/189156638-723bc889-422e-4943-ae71-7da104b443fe.png)

**Comment by leeisme1** [comment]
Đã xử lý.
